# Generated by Django 3.1.6 on 2021-02-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=264),
        ),
    ]
